// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\cust_arch_22\cust_architecture_tc.v
// Created: 2019-10-11 18:41:20
// 
// Generated by MATLAB 9.7 and HDL Coder 3.15
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cust_architecture_tc
// Source Path: cust_architecture_tc
// Hierarchy Level: 1
// 
// Master clock enable input: clk_enable
// 
// enb_108_1_1 : identical to clk_enable
// enb         : 108x slower than clk with last phase
// enb_1_1_1   : 108x slower than clk with phase 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cust_architecture_tc
          (clk,
           reset,
           clk_enable,
           enb_108_1_1,
           enb,
           enb_1_1_1);


  input   clk;
  input   reset;
  input   clk_enable;
  output  enb_108_1_1;
  output  enb;
  output  enb_1_1_1;


  reg [6:0] count108;  // ufix7
  wire phase_all;
  reg  phase_0;
  wire phase_0_tmp;
  reg  phase_1;
  wire phase_1_tmp;


  always @ (posedge clk or posedge reset)
    begin: Counter108
      if (reset == 1'b1) begin
        count108 <= 7'b0000001;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (count108 >= 7'b1101011) begin
            count108 <= 7'b0000000;
          end
          else begin
            count108 <= count108 + 7'b0000001;
          end
        end
      end
    end // Counter108

  assign phase_all = clk_enable ? 1'b1 : 1'b0;

  always @ (posedge clk or posedge reset)
    begin: temp_process1
      if (reset == 1'b1) begin
        phase_0 <= 1'b0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          phase_0 <= phase_0_tmp;
        end
      end
    end // temp_process1

  assign  phase_0_tmp = (count108 == 7'b1101011 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  always @ (posedge clk or posedge reset)
    begin: temp_process2
      if (reset == 1'b1) begin
        phase_1 <= 1'b1;
      end
      else begin
        if (clk_enable == 1'b1) begin
          phase_1 <= phase_1_tmp;
        end
      end
    end // temp_process2

  assign  phase_1_tmp = (count108 == 7'b0000000 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign enb_108_1_1 =  phase_all & clk_enable;

  assign enb =  phase_0 & clk_enable;

  assign enb_1_1_1 =  phase_1 & clk_enable;


endmodule  // cust_architecture_tc

