// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\cust_arch_22\filter_nw.v
// Created: 2019-10-11 18:41:20
// 
// Generated by MATLAB 9.7 and HDL Coder 3.15
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: filter_nw
// Source Path: 
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module filter_nw
          (clk,
           reset,
           enb_108_1_1,
           in0,
           Trigger_emulated,
           out0);


  input   clk;
  input   reset;
  input   enb_108_1_1;
  input   signed [15:0] in0;  // sfix16_En15
  input   Trigger_emulated;
  output  signed [15:0] out0;  // sfix16_En11


  wire enb_108_1_1_gated;
  wire signed [15:0] filter_out1_reg;  // sfix16_En11


  assign enb_108_1_1_gated = Trigger_emulated && enb_108_1_1;

  filter_block u_filter_block (.clk(clk),
                               .enb_108_1_1_gated(enb_108_1_1_gated),
                               .reset(reset),
                               .filter_block_in(in0),  // sfix16_En15
                               .filter_block_out(filter_out1_reg)  // sfix16_En11
                               );

  assign out0 = filter_out1_reg;

endmodule  // filter_nw

