// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\cust_arch_16\get_enabled_timings_1.v
// Created: 2019-09-03 15:21:09
// 
// Generated by MATLAB 9.5 and HDL Coder 3.13
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: get_enabled_timings_1
// Source Path: cust_arch_16/cust_architecture/get enabled timings 1
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module get_enabled_timings_1
          (input_state,
           write_to,
           write_enable_6to15);


  input   [7:0] input_state;  // uint8
  input   write_to;
  output  write_enable_6to15;


  wire Compare_To_Constant2_out1;
  wire Compare_To_Constant3_out1;
  wire AND_out1;
  wire switch_compare_1;
  wire Constant_out1;
  wire Switch3_out1;


  assign Compare_To_Constant2_out1 = input_state >= 8'b00000110;



  assign Compare_To_Constant3_out1 = input_state <= 8'b00001111;



  assign AND_out1 = Compare_To_Constant2_out1 & Compare_To_Constant3_out1;



  assign switch_compare_1 = AND_out1 > 1'b0;



  assign Constant_out1 = 1'b0;



  assign Switch3_out1 = (switch_compare_1 == 1'b0 ? Constant_out1 :
              write_to);



  assign write_enable_6to15 = Switch3_out1;

endmodule  // get_enabled_timings_1

