// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\cust_arch_16\High_pass.v
// Created: 2019-09-02 09:23:26
// 
// Generated by MATLAB 9.5 and HDL Coder 3.13
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: High_pass
// Source Path: cust_arch_16/cust_architecture/one_pole_IIR/High_pass
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module High_pass
          (Input_rsvd,
           Input1,
           Output_rsvd,
           Output1);


  input   signed [15:0] Input_rsvd;  // sfix16_En15
  input   signed [15:0] Input1;  // sfix16_En15
  output  signed [32:0] Output_rsvd;  // sfix33_En29
  output  signed [15:0] Output1;  // sfix16_En15


  wire signed [31:0] s_1_mul_temp;  // sfix32_En30
  wire signed [15:0] s_1_out1;  // sfix16_En11
  wire signed [31:0] a_2_1_out1;  // sfix32_En30
  wire signed [33:0] SumA21_sub_cast;  // sfix34_En30
  wire signed [33:0] SumA21_sub_cast_1;  // sfix34_En30
  wire signed [33:0] SumA21_out1;  // sfix34_En30
  wire signed [15:0] CastState1_out1;  // sfix16_En15
  wire signed [33:0] SumB21_sub_cast;  // sfix34_En30
  wire signed [33:0] SumB21_sub_cast_1;  // sfix34_En30
  wire signed [33:0] SumB21_out1;  // sfix34_En30
  wire signed [32:0] ConvertOut_out1;  // sfix33_En29


  assign s_1_mul_temp = 16'sb0111110000011010 * Input_rsvd;
  assign s_1_out1 = ({{3{s_1_mul_temp[31]}}, s_1_mul_temp[31:19]}) + $signed({1'b0, s_1_mul_temp[18] & (s_1_mul_temp[19] | (|s_1_mul_temp[17:0]))});



  assign a_2_1_out1 = 16'sb1000011111001101 * Input1;



  assign SumA21_sub_cast = {s_1_out1[14:0], 19'b0000000000000000000};
  assign SumA21_sub_cast_1 = {{2{a_2_1_out1[31]}}, a_2_1_out1};
  assign SumA21_out1 = SumA21_sub_cast - SumA21_sub_cast_1;



  assign CastState1_out1 = SumA21_out1[30:15] + $signed({1'b0, SumA21_out1[14] & (SumA21_out1[15] | (|SumA21_out1[13:0]))});



  assign SumB21_sub_cast = {{3{CastState1_out1[15]}}, {CastState1_out1, 15'b000000000000000}};
  assign SumB21_sub_cast_1 = {{3{Input1[15]}}, {Input1, 15'b000000000000000}};
  assign SumB21_out1 = SumB21_sub_cast - SumB21_sub_cast_1;



  assign ConvertOut_out1 = SumB21_out1[33:1] + $signed({1'b0, SumB21_out1[1] & SumB21_out1[0]});



  assign Output_rsvd = ConvertOut_out1;

  assign Output1 = CastState1_out1;

endmodule  // High_pass

