// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\cust_arch_16\offset_to_int16.v
// Created: 2019-08-30 15:36:56
// 
// Generated by MATLAB 9.5 and HDL Coder 3.13
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: offset_to_int16
// Source Path: cust_arch_16/cust_architecture/offset_to_int16
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module offset_to_int16
          (In1,
           Out1);


  input   signed [15:0] In1;  // sfix16_En15
  output  signed [15:0] Out1;  // int16


  wire signed [31:0] Gain5_out1;  // sfix32_En15
  wire [15:0] Constant5_out1;  // uint16
  wire signed [32:0] Subtract1_add_cast;  // sfix33_En15
  wire signed [32:0] Subtract1_add_cast_1;  // sfix33_En15
  wire signed [32:0] Subtract1_out1;  // sfix33_En15
  wire signed [15:0] Data_Type_Conversion5_out1;  // int16


  assign Gain5_out1 = 16'sb0111111111111111 * In1;



  assign Constant5_out1 = 16'b1000000000000000;



  assign Subtract1_add_cast = {Gain5_out1[31], Gain5_out1};
  assign Subtract1_add_cast_1 = {2'b0, {Constant5_out1, 15'b000000000000000}};
  assign Subtract1_out1 = Subtract1_add_cast + Subtract1_add_cast_1;



  assign Data_Type_Conversion5_out1 = Subtract1_out1[30:15];



  assign Out1 = Data_Type_Conversion5_out1;

endmodule  // offset_to_int16

