vlib work
vlog  Output_State_to_RAM_address_to_read.v
vlog  Detect_change_ch_cnt.v
vlog  find_next_chip_rollmap.v
vlog  reading_address.v
vlog  get_enabled_timings.v
vlog  Interpret_to_RAM_output.v
vlog  OutputStateMachine.v
vlog  output_interpret.v
vlog  RAM_address_definition.v
vlog  condition_to_count_DAC_or_ADC.v
vlog  RAM_address_channel_data.v
vlog  enable_source_chip_transmission.v
vlog  find_first_one_pos.v
vlog  find_next_chip_rollmap_block.v
vlog  get_sources_and_RAM_addresses.v
vlog  interpret_incoming_data.v
vlog  Interpret_to_RAM_input.v
vlog  DualPortRAM_generic.v
vlog  store_and_retrieve_input.v
vlog  InputStateMachine.v
vlog  input_interpret_store_retrieve.v
vlog  Detect_Change2.v
vlog  Detect_Change3.v
vlog  current_value_enable.v
vlog  currest_address_enable.v
vlog  HP_Butter_2nd.v
vlog  digital_filter.v
vlog  filter_change.v
vlog  preovious_change.v
vlog  SimpleDualPortRAM_generic.v
vlog  FIFO_filter.v
vlog  FIFO_previous_sample.v
vlog  FilterChip1.v
vlog  process_and_retrieve.v
vlog  get_data_only_when_enabled.v
vlog  getting_address_and_enable_for_Magic_and_Timestamps.v
vlog  read_from_magic_and_timestamp.v
vlog  collect_output.v
vlog  cust_architecture.v
