// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\CustArch_v16\currest_address_enable.v
// Created: 2021-06-21 17:49:55
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: currest_address_enable
// Source Path: CustArch_v16/cust_architecture/process_and_retrieve/FilterChip1/currest_address_enable
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module currest_address_enable
          (clk,
           reset,
           enb,
           address_for_processing,
           Enable,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  input   [8:0] address_for_processing;  // ufix9
  input   Enable;
  output  [8:0] Out1;  // ufix9


  wire enb_gated;
  wire [8:0] address_for_processing_bypass;  // ufix9
  reg [8:0] address_for_processing_last_value;  // ufix9


  assign enb_gated = Enable && enb;

  always @(posedge clk or posedge reset)
    begin : Out1_bypass_process
      if (reset == 1'b1) begin
        address_for_processing_last_value <= 9'b000000000;
      end
      else begin
        if (enb_gated) begin
          address_for_processing_last_value <= address_for_processing_bypass;
        end
      end
    end



  assign address_for_processing_bypass = (Enable == 1'b0 ? address_for_processing_last_value :
              address_for_processing);



  assign Out1 = address_for_processing_bypass;

endmodule  // currest_address_enable

