open_system('gm_pipe_in_v4');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve', 0, 1, 'cp : 20.754 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input', 0, 2, 'cp : 20.754 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 0, 1, 'cp : 0 ns');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 1, 4, 'cp : 20.754 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data', 0, 2, 'cp : 20.754 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses', 0, 4, 'cp : 20.754 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos', 0, 1, 'cp : 9.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap', 0, 1, 'cp : 17.634 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/AND2', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/AND2', 0, 1, 'cp : 20.754 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/Compare To Constant1', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/Compare To Constant1', 0, 1, 'cp : 1.451 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/Compare To Constant5', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/Compare To Constant5', 0, 1, 'cp : 19.085 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/Switch', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/Switch', 0, 1, 'cp : 2.418 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Bit Slice7', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Bit Slice7', 0, 1, 'cp : 2.418 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Compare To Constant7', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Compare To Constant7', 0, 1, 'cp : 3.869 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch', 0, 1, 'cp : 9.33 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch1', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch1', 0, 1, 'cp : 8.688 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch2', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch2', 0, 1, 'cp : 8.046 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch3', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch3', 0, 1, 'cp : 7.404 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch4', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch4', 0, 1, 'cp : 6.762 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch5', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch5', 0, 1, 'cp : 6.12 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch6', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch6', 0, 1, 'cp : 5.478 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch7', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch7', 0, 1, 'cp : 4.836 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Bitwise AND', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Bitwise AND', 0, 1, 'cp : 16.992 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Bitwise AND1', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Bitwise AND1', 0, 1, 'cp : 17.634 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Compare To Constant7', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Compare To Constant7', 0, 1, 'cp : 10.781 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch', 0, 1, 'cp : 16.242 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch1', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch1', 0, 1, 'cp : 15.6 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch2', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch2', 0, 1, 'cp : 14.958 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch3', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch3', 0, 1, 'cp : 14.316 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch4', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch4', 0, 1, 'cp : 13.674 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch5', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch5', 0, 1, 'cp : 13.032 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch6', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch6', 0, 1, 'cp : 12.39 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch7', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch7', 0, 1, 'cp : 11.748 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 0, 1, 'cp : 0 ns');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 4, 'cp : 20.754 ns');
