SLStudio.Utils.RemoveHighlighting(get_param('CustArch_v22', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_CustArch_v22', 'handle'));
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve', 0, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection', 0, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/ProcessedData_storage', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/ProcessedData_storage', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/ProcessedData_storage', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/ProcessedData_storage', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold', 0, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation', 0, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-2', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-2', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-2', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-2', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation', 0, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/n', 0, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/rms', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/rms', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/rms', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/rms', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/rms', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/square_sum', 0, 2, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/square_sum', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/square_sum', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/square_sum', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/square_sum', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/Square Root1', 0, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/Square Root1', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/Square Root1', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/Square Root1', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/Square Root1', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation/rms_gain', 0, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation/Add', 0, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation/Add1', 0, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation/Add4', 0, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation/Switch1', 0, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/buffer_counter/square_sum', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/buffer_counter/square_sum', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/buffer_counter/square_sum', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/LocalMaximaAdaptiveThreshold/RMS_computation/buffer_counter/square_sum', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/refractory_period/spikes', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/refractory_period/spikes', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/refractory_period/spikes', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/refractory_period/spikes', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/refractory_period/timestamp_before', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/refractory_period/timestamp_before', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/refractory_period/timestamp_before', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/process_and_retrieve/spike_detection/refractory_period/timestamp_before', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 1, 1, '');
annotate_port('gm_CustArch_v22/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/output_interpret/OutputStateMachine', 1, 1, '');
annotate_port('CustArch_v22/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 0, 2, '');
annotate_port('CustArch_v22/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
