vlib work
vlog  DualPortRAM_generic.v
vlog  LocalMaxima.v
vlog  adaptive_th_computation.v
vlog  buffer_counter.v
vlog  NewtonPolynomialIVStage.v
vlog  Square_Root1_iv.v
vlog  Square_Root1_core.v
vlog  Square_Root1.v
vlog  RMS_computation.v
vlog  LocalMaximaAdaptiveThreshold.v
vlog  refractory_period.v
vlog  spike_detection.v
