open_system('gm_LocalMaximaAdaptiveThreshold');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/RMS_computation', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation', 0, 1, 'cp : 132.127 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation', 0, 1, 'cp : 131.835 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/RMS_computation/n', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/n', 0, 1, 'cp : 11.98 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/RMS_computation/rms', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/rms', 1, 1, 'cp : 132.127 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/RMS_computation/square_sum', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/square_sum', 0, 2, 'cp : 2.372 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/RMS_computation/Square Root1', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/Square Root1', 0, 1, 'cp : 127.315 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation/rms_gain', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation/rms_gain', 0, 1, 'cp : 129.623 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation/Add', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation/Add', 0, 1, 'cp : 128.469 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation/Add1', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation/Add1', 0, 1, 'cp : 129.623 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation/Add4', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation/Add4', 0, 1, 'cp : 130.777 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation/Switch1', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation/Switch1', 0, 1, 'cp : 131.835 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 'user1');
annotate_port('LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 0, 2, 'cp : 2.372 ns');
annotate_port('LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 1, 1, 'cp : 132.127 ns');
