open_system('LocalMaximaAdaptiveThreshold');
open_system('gm_LocalMaximaAdaptiveThreshold');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 1, 1, 'Block not characterized');
hilite_system('LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 'user2');
annotate_port('LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 1, 1, 'Block not characterized');
hilite_system('LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 'user2');
annotate_port('LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-2', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-2', 1, 1, 'Block not characterized');
hilite_system('LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-2', 'user2');
annotate_port('LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-2', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-2', 1, 1, 'Block not characterized');
hilite_system('LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-2', 'user2');
annotate_port('LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/RMS_computation/rms', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/rms', 1, 1, 'Block not characterized');
hilite_system('LocalMaximaAdaptiveThreshold/RMS_computation/rms', 'user2');
annotate_port('LocalMaximaAdaptiveThreshold/RMS_computation/rms', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/RMS_computation/rms', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/rms', 1, 1, 'Block not characterized');
hilite_system('LocalMaximaAdaptiveThreshold/RMS_computation/rms', 'user2');
annotate_port('LocalMaximaAdaptiveThreshold/RMS_computation/rms', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/RMS_computation/square_sum', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/square_sum', 1, 1, 'Block not characterized');
hilite_system('LocalMaximaAdaptiveThreshold/RMS_computation/square_sum', 'user2');
annotate_port('LocalMaximaAdaptiveThreshold/RMS_computation/square_sum', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/RMS_computation/square_sum', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/square_sum', 1, 1, 'Block not characterized');
hilite_system('LocalMaximaAdaptiveThreshold/RMS_computation/square_sum', 'user2');
annotate_port('LocalMaximaAdaptiveThreshold/RMS_computation/square_sum', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/RMS_computation/Square Root1', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/Square Root1', 1, 1, 'Block not characterized');
hilite_system('LocalMaximaAdaptiveThreshold/RMS_computation/Square Root1', 'user2');
annotate_port('LocalMaximaAdaptiveThreshold/RMS_computation/Square Root1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/RMS_computation/Square Root1', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/Square Root1', 1, 1, 'Block not characterized');
hilite_system('LocalMaximaAdaptiveThreshold/RMS_computation/Square Root1', 'user2');
annotate_port('LocalMaximaAdaptiveThreshold/RMS_computation/Square Root1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/RMS_computation/buffer_counter/square_sum', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/buffer_counter/square_sum', 1, 1, 'Block not characterized');
hilite_system('LocalMaximaAdaptiveThreshold/RMS_computation/buffer_counter/square_sum', 'user2');
annotate_port('LocalMaximaAdaptiveThreshold/RMS_computation/buffer_counter/square_sum', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_LocalMaximaAdaptiveThreshold/RMS_computation/buffer_counter/square_sum', 'user2');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/buffer_counter/square_sum', 1, 1, 'Block not characterized');
hilite_system('LocalMaximaAdaptiveThreshold/RMS_computation/buffer_counter/square_sum', 'user2');
annotate_port('LocalMaximaAdaptiveThreshold/RMS_computation/buffer_counter/square_sum', 1, 1, 'Block not characterized');
