open_system('CustArch_v21');
open_system('gm_CustArch_v21');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/filtering', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/Rate Transition1', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/Rate Transition1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/Rate Transition1', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/Rate Transition1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR/HP_Butter_2nd', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR/HP_Butter_2nd', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR/HP_Butter_2nd', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR/HP_Butter_2nd', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR/HP_Butter_2nd/delay_3', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR/HP_Butter_2nd/delay_3', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR/HP_Butter_2nd/delay_3', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR/HP_Butter_2nd/delay_3', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR/HP_Butter_2nd/delay_7', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR/HP_Butter_2nd/delay_7', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR/HP_Butter_2nd/delay_7', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR/HP_Butter_2nd/delay_7', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR/HP_Butter_2nd/delay_9', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR/HP_Butter_2nd/delay_9', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR/HP_Butter_2nd/delay_9', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR/HP_Butter_2nd/delay_9', 1, 1, 'Obstacle to clock-rate pipelining');
