open_system('CustArch_v21');
open_system('gm_CustArch_v21');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 'user2');
annotate_port('CustArch_v21/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 'user2');
annotate_port('CustArch_v21/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 'user2');
annotate_port('CustArch_v21/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 'user2');
annotate_port('CustArch_v21/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 'user2');
annotate_port('CustArch_v21/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 'user2');
annotate_port('CustArch_v21/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 'user2');
annotate_port('CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 'user2');
annotate_port('CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 'user2');
annotate_port('CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 'user2');
annotate_port('CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 'user2');
annotate_port('CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 'user2');
annotate_port('CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 'user2');
annotate_port('CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 'user2');
annotate_port('CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 'user2');
annotate_port('CustArch_v21/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/ProcessedData_storage', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/ProcessedData_storage', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/ProcessedData_storage', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/ProcessedData_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/ProcessedData_storage', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/ProcessedData_storage', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/ProcessedData_storage', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/ProcessedData_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-1', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-1', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-1', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-1', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-1', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-1', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-2', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-2', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-2', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-2', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-2', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-2', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/refractory_period/spikes', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/refractory_period/spikes', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/refractory_period/spikes', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/refractory_period/spikes', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/refractory_period/spikes', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/refractory_period/spikes', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/refractory_period/spikes', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/refractory_period/spikes', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/refractory_period/timestamp_before', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/refractory_period/timestamp_before', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/refractory_period/timestamp_before', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/refractory_period/timestamp_before', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/refractory_period/timestamp_before', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/refractory_period/timestamp_before', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/refractory_period/timestamp_before', 'user2');
annotate_port('CustArch_v21/cust_architecture/process_and_retrieve/spike_detection/refractory_period/timestamp_before', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 'user2');
annotate_port('CustArch_v21/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 'user2');
annotate_port('gm_CustArch_v21/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 1, 1, 'Block not characterized');
hilite_system('CustArch_v21/cust_architecture/output_interpret/OutputStateMachine', 'user2');
annotate_port('CustArch_v21/cust_architecture/output_interpret/OutputStateMachine', 1, 1, 'Block not characterized');
