// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\CustArch_v10\digital_filter.v
// Created: 2021-05-25 15:05:50
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: digital_filter
// Source Path: CustArch_v10/cust_architecture/process_and_retrieve/digital_filter
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module digital_filter
          (current_sample,
           previous_sample_0,
           previous_sample_1,
           filter_output,
           new_previous_sample);


  input   [15:0] current_sample;  // uint16
  input   signed [31:0] previous_sample_0;  // sfix32_En9
  input   signed [31:0] previous_sample_1;  // sfix32_En9
  output  [15:0] filter_output;  // uint16
  output  signed [31:0] new_previous_sample;  // sfix32_En9


  wire [15:0] Constant_out1;  // uint16
  wire signed [16:0] Subtract_sub_temp;  // sfix17
  wire signed [16:0] Subtract_1;  // sfix17
  wire signed [16:0] Subtract_2;  // sfix17
  wire signed [15:0] Subtract_out1;  // sfix16_En1
  wire signed [31:0] HP_Butter_2nd_out1;  // sfix32_En20
  wire signed [31:0] HP_Butter_2nd_out2;  // sfix32_En9
  wire [15:0] Constant1_out1;  // uint16
  wire signed [37:0] Subtract1_add_cast;  // sfix38_En20
  wire signed [37:0] Subtract1_add_cast_1;  // sfix38_En20
  wire signed [37:0] Subtract1_add_temp;  // sfix38_En20
  wire [15:0] Subtract1_out1;  // uint16


  assign Constant_out1 = 16'b1000000000000000;



  assign Subtract_1 = {1'b0, current_sample};
  assign Subtract_2 = {1'b0, Constant_out1};
  assign Subtract_sub_temp = Subtract_1 - Subtract_2;
  assign Subtract_out1 = {Subtract_sub_temp[14:0], 1'b0};



  HP_Butter_2nd u_HP_Butter_2nd (.new_raw(Subtract_out1),  // sfix16_En1
                                 .previous_samples_0(previous_sample_0),  // sfix32_En9
                                 .previous_samples_1(previous_sample_1),  // sfix32_En9
                                 .new_fitlered(HP_Butter_2nd_out1),  // sfix32_En20
                                 .new_previous(HP_Butter_2nd_out2)  // sfix32_En9
                                 );

  assign Constant1_out1 = 16'b1000000000000000;



  assign Subtract1_add_cast = {{6{HP_Butter_2nd_out1[31]}}, HP_Butter_2nd_out1};
  assign Subtract1_add_cast_1 = {2'b0, {Constant1_out1, 20'b00000000000000000000}};
  assign Subtract1_add_temp = Subtract1_add_cast + Subtract1_add_cast_1;
  assign Subtract1_out1 = Subtract1_add_temp[35:20];



  assign filter_output = Subtract1_out1;

  assign new_previous_sample = HP_Butter_2nd_out2;

endmodule  // digital_filter

