SLStudio.Utils.RemoveHighlighting(get_param('CustArch_v4', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_CustArch_v4', 'handle'));
annotate_port('gm_CustArch_v4/cust_architecture/input_interpret_store_retrieve', 0, 3, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve', 1, 3, '');
annotate_port('gm_CustArch_v4/cust_architecture/collect_output/Bit Set to get AC during DC', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/collect_output/Bit Set to get AC during DC', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input', 0, 2, '');
annotate_port('gm_CustArch_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 0, 2, '');
annotate_port('gm_CustArch_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/DCtoAC_storage', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/DCtoAC_storage', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/process_and_retrieve/DCtoAC_storage', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/DCtoAC_storage', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/process_and_retrieve/DCtoAC_storage', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass/multiplier', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass/dtc', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass/dtc1', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass/dtc2', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass/gain', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass/dtc3', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass/Sub', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass/dtc5', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass/dtc6', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass/Sub1', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass/dtc8', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass/dtc9', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass/adder', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass/adder1', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass/dtc10', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass/output_typeconvert_wire', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass/highpass_out1', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass/Add_out1bypassMux', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass/Add', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/process_and_retrieve/bandpass/Add1', 0, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 1, 1, '');
annotate_port('gm_CustArch_v4/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/output_interpret/OutputStateMachine', 1, 1, '');
annotate_port('CustArch_v4/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 0, 2, '');
annotate_port('CustArch_v4/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
