SLStudio.Utils.RemoveHighlighting(get_param('CustArch', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_CustArch', 'handle'));
annotate_port('gm_CustArch/cust_architecture/input_interpret_store_retrieve', 0, 3, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve', 1, 3, '');
annotate_port('gm_CustArch/cust_architecture/collect_output/Bit Set to get AC during DC', 1, 1, '');
annotate_port('CustArch/cust_architecture/collect_output/Bit Set to get AC during DC', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('CustArch/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('CustArch/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input', 0, 2, '');
annotate_port('gm_CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 0, 2, '');
annotate_port('gm_CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Detect Change', 1, 1, '');
annotate_port('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Detect Change', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate', 1, 1, '');
annotate_port('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate1', 1, 1, '');
annotate_port('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate1', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate2', 1, 1, '');
annotate_port('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate2', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate3', 1, 1, '');
annotate_port('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate3', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate4', 1, 1, '');
annotate_port('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate4', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate5', 1, 1, '');
annotate_port('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate5', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate6', 1, 1, '');
annotate_port('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate6', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Triggered Subsystem/Bit Rotate', 1, 1, '');
annotate_port('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Triggered Subsystem/Bit Rotate', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/HPF_storage', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/HPF_storage', 1, 1, '');
annotate_port('CustArch/cust_architecture/process_and_retrieve/HPF_storage', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/HPF_storage', 1, 1, '');
annotate_port('CustArch/cust_architecture/process_and_retrieve/HPF_storage', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/LPF_storage', 1, 1, '');
annotate_port('CustArch/cust_architecture/process_and_retrieve/LPF_storage', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/LPF_storage', 1, 1, '');
annotate_port('CustArch/cust_architecture/process_and_retrieve/LPF_storage', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/Switch', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/multiplier', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc1', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc2', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/gain', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc3', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc5', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc6', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub1', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc8', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc9', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/adder', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc10', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/multiplier3', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc11', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc12', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc13', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/gain2', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc14', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub2', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc16', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc17', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub3', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc19', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc20', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/adder1', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc21', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/multiplier6', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc22', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc23', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc24', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/gain4', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc25', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub4', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc27', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc28', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub5', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc30', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc31', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/adder2', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc32', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/multiplier9', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc33', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc34', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc35', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/gain6', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc36', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub6', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc38', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc39', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub7', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc41', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc42', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/adder3', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc43', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/multiplier12', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc44', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc45', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc46', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/gain8', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc47', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub8', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc49', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc50', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub9', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc52', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc53', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/adder4', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc54', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/multiplier15', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc55', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc56', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc57', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/gain10', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc58', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub10', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc60', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc61', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub11', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc63', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc64', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/adder5', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc65', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/multiplier18', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc66', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc67', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc68', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/gain12', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc69', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub12', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc71', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc72', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub13', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc74', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc75', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/adder6', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc76', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/multiplier21', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc77', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc78', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc79', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/gain14', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc80', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub14', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc82', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc83', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub15', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc85', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc86', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/adder7', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc87', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/multiplier24', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc88', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc89', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc90', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/gain16', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc91', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub16', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc93', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc94', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub17', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc96', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc97', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/adder8', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc98', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/multiplier27', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc99', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc100', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc101', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/gain18', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc102', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub18', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc104', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc105', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub19', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc107', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc108', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/adder9', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc109', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/multiplier30', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc110', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc111', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc112', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/gain20', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc113', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub20', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc115', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc116', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub21', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc118', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc119', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/adder10', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc120', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/multiplier33', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc121', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc122', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc123', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/gain22', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc124', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub22', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc126', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc127', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub23', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc129', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc130', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/adder11', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc131', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/multiplier36', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc132', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc133', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc134', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/gain24', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc135', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub24', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc137', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc138', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub25', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc140', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc141', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/adder12', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc142', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/multiplier39', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc143', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc144', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc145', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/gain26', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc146', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub26', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc148', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc149', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub27', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc151', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc152', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/adder13', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc153', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/multiplier42', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc154', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc155', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc156', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/gain28', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc157', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub28', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc159', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc160', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub29', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc162', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc163', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/adder14', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc164', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/multiplier45', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc165', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc166', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc167', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/gain30', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc168', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub30', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc170', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc171', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub31', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc173', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc174', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/adder15', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc175', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/multiplier48', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc176', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc177', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc178', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/gain32', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc179', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub32', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc181', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc182', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub33', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc184', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc185', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/adder16', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc186', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/multiplier51', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc187', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc188', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc189', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/gain34', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc190', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub34', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc192', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc193', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Sub35', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc195', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc196', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/adder17', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/dtc197', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/output_typeconvert_wire', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/filter_out1', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter/Input Quantizer', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 1, '');
annotate_port('CustArch/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 1, 1, '');
annotate_port('CustArch/cust_architecture/output_interpret/OutputStateMachine', 1, 1, '');
annotate_port('CustArch/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 0, 2, '');
annotate_port('CustArch/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Filter', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Gain', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Data Type  Conversion1_out1bypassMux', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Data Type  Conversion', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Data Type  Conversion1', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Subtract1', 0, 1, '');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/80-120Hz IIR/controlss_temp/Subtract2', 0, 1, '');
