open_system('CustArch');
open_system('gm_CustArch');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/collect_output/Bit Set to get AC during DC', 'user2');
annotate_port('gm_CustArch/cust_architecture/collect_output/Bit Set to get AC during DC', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/collect_output/Bit Set to get AC during DC', 'user2');
annotate_port('CustArch/cust_architecture/collect_output/Bit Set to get AC during DC', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 'user2');
annotate_port('gm_CustArch/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 'user2');
annotate_port('CustArch/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 'user2');
annotate_port('gm_CustArch/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 'user2');
annotate_port('CustArch/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 'user2');
annotate_port('gm_CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 'user2');
annotate_port('CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 'user2');
annotate_port('gm_CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 'user2');
annotate_port('CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 'user2');
annotate_port('gm_CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 'user2');
annotate_port('CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 'user2');
annotate_port('gm_CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 'user2');
annotate_port('CustArch/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Detect Change', 'user2');
annotate_port('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Detect Change', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Detect Change', 'user2');
annotate_port('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Detect Change', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate', 'user2');
annotate_port('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate', 'user2');
annotate_port('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate1', 'user2');
annotate_port('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate1', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate1', 'user2');
annotate_port('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate2', 'user2');
annotate_port('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate2', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate2', 'user2');
annotate_port('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate3', 'user2');
annotate_port('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate3', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate3', 'user2');
annotate_port('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate4', 'user2');
annotate_port('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate4', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate4', 'user2');
annotate_port('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate5', 'user2');
annotate_port('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate5', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate5', 'user2');
annotate_port('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate6', 'user2');
annotate_port('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate6', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate6', 'user2');
annotate_port('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Triggered Subsystem/Bit Rotate', 'user2');
annotate_port('gm_CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Triggered Subsystem/Bit Rotate', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Triggered Subsystem/Bit Rotate', 'user2');
annotate_port('CustArch/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Triggered Subsystem/Bit Rotate', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/process_and_retrieve/HPF_storage', 'user2');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/HPF_storage', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/process_and_retrieve/HPF_storage', 'user2');
annotate_port('CustArch/cust_architecture/process_and_retrieve/HPF_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/process_and_retrieve/HPF_storage', 'user2');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/HPF_storage', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/process_and_retrieve/HPF_storage', 'user2');
annotate_port('CustArch/cust_architecture/process_and_retrieve/HPF_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/process_and_retrieve/LPF_storage', 'user2');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/LPF_storage', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/process_and_retrieve/LPF_storage', 'user2');
annotate_port('CustArch/cust_architecture/process_and_retrieve/LPF_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/process_and_retrieve/LPF_storage', 'user2');
annotate_port('gm_CustArch/cust_architecture/process_and_retrieve/LPF_storage', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/process_and_retrieve/LPF_storage', 'user2');
annotate_port('CustArch/cust_architecture/process_and_retrieve/LPF_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 'user2');
annotate_port('gm_CustArch/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 'user2');
annotate_port('gm_CustArch/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 'user2');
annotate_port('CustArch/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 'user2');
annotate_port('gm_CustArch/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 'user2');
annotate_port('gm_CustArch/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 1, 1, 'Block not characterized');
hilite_system('CustArch/cust_architecture/output_interpret/OutputStateMachine', 'user2');
annotate_port('CustArch/cust_architecture/output_interpret/OutputStateMachine', 1, 1, 'Block not characterized');
