// -------------------------------------------------------------
// 
// File Name: C:\GitHub\closed-loop-neuroscience\Mattia\Custom_architecture\Verilog\CustArch\pipe_in_interpret.v
// Created: 2021-03-29 11:16:01
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: pipe_in_interpret
// Source Path: CustArch/cust_architecture/pipe_in_interpret
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module pipe_in_interpret
          (clk,
           reset,
           enb,
           In1,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  input   [15:0] In1;  // uint16
  output  [15:0] Out1;  // uint16


  reg [15:0] Memory6_out1;  // uint16
  wire [7:0] Bit_Slice1_out1;  // uint8
  wire Compare_To_Constant1_out1;
  wire switch_compare_1;
  wire [15:0] Constant4_out1;  // uint16
  wire [15:0] Switch1_out1;  // uint16


  always @(posedge clk or posedge reset)
    begin : Memory6_process
      if (reset == 1'b1) begin
        Memory6_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Memory6_out1 <= In1;
        end
      end
    end



  assign Bit_Slice1_out1 = Memory6_out1[15:8];



  assign Compare_To_Constant1_out1 = Bit_Slice1_out1 == 8'b00000010;



  assign switch_compare_1 = Compare_To_Constant1_out1 > 1'b0;



  assign Constant4_out1 = 16'b0000000000000101;



  assign Switch1_out1 = (switch_compare_1 == 1'b0 ? Constant4_out1 :
              In1);



  assign Out1 = Switch1_out1;

endmodule  // pipe_in_interpret

