SLStudio.Utils.RemoveHighlighting(get_param('CustArch_v13', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_CustArch_v13', 'handle'));
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/collect_output/Bit Set to get AC during DC', 1, 1, '');
annotate_port('CustArch_v13/cust_architecture/collect_output/Bit Set to get AC during DC', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('CustArch_v13/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('CustArch_v13/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('CustArch_v13/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('CustArch_v13/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 1, 1, '');
annotate_port('CustArch_v13/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 1, 1, '');
annotate_port('CustArch_v13/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 1, 1, '');
annotate_port('CustArch_v13/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 1, 1, '');
annotate_port('CustArch_v13/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 1, 1, '');
annotate_port('CustArch_v13/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 1, 1, '');
annotate_port('CustArch_v13/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 1, 1, '');
annotate_port('CustArch_v13/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 1, 1, '');
annotate_port('CustArch_v13/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 1, 1, '');
annotate_port('CustArch_v13/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Memory3', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/ProcessedData_storage1', 1, 1, '');
annotate_port('CustArch_v13/cust_architecture/process_and_retrieve/ProcessedData_storage1', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/ProcessedData_storage1', 1, 1, '');
annotate_port('CustArch_v13/cust_architecture/process_and_retrieve/ProcessedData_storage1', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/Rate Transition', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/Add1_out1bypassMux', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/Add', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/Add1', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/t', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/filter_in_0_wire', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/multiplier', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc1', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc2', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/gain', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc3', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/Sub', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc5', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc6', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/Sub1', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc8', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/adder', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/adder1', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc9', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/output_typeconvert_wire', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/mux', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/filter_out_1', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/filter_out1', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/Input Quantizer', 0, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 1, '');
annotate_port('CustArch_v13/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 1, 1, '');
annotate_port('gm_CustArch_v13/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 1, 1, '');
annotate_port('CustArch_v13/cust_architecture/output_interpret/OutputStateMachine', 1, 1, '');
