open_system('CustArch_v13');
open_system('gm_CustArch_v13');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/collect_output', 'user2');
hilite_system('CustArch_v13/cust_architecture/collect_output', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve', 'user2');
hilite_system('CustArch_v13/cust_architecture/process_and_retrieve', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1', 'user2');
hilite_system('CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Subsystem', 'user2');
hilite_system('CustArch_v13/cust_architecture/process_and_retrieve/Subsystem', 'user2');
