open_system('CustArch_v20');
open_system('gm_CustArch_v20');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v20/cust_architecture/process_and_retrieve/two_pole_IIR', 'user5');
hilite_system('CustArch_v20/cust_architecture/process_and_retrieve/two_pole_IIR', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v20/cust_architecture/process_and_retrieve/PreviousData1_storage', 'user5');
hilite_system('CustArch_v20/cust_architecture/process_and_retrieve/PreviousData1_storage', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v20/cust_architecture/process_and_retrieve/PreviousData1_storage', 'user5');
hilite_system('CustArch_v20/cust_architecture/process_and_retrieve/PreviousData1_storage', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v20/cust_architecture/process_and_retrieve/PreviousData2_storage', 'user5');
hilite_system('CustArch_v20/cust_architecture/process_and_retrieve/PreviousData2_storage', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v20/cust_architecture/process_and_retrieve/PreviousData2_storage', 'user5');
hilite_system('CustArch_v20/cust_architecture/process_and_retrieve/PreviousData2_storage', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('CustArch_v20/cust_architecture/process_and_retrieve/Mux', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v20/cust_architecture/process_and_retrieve/two_pole_IIR/HP_Butter_2nd', 'user5');
hilite_system('CustArch_v20/cust_architecture/process_and_retrieve/two_pole_IIR/HP_Butter_2nd', 'user5');
