SLStudio.Utils.RemoveHighlighting(get_param('CustArch_v5', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_CustArch_v5', 'handle'));
annotate_port('gm_CustArch_v5/cust_architecture/input_interpret_store_retrieve', 0, 3, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve', 1, 3, '');
annotate_port('gm_CustArch_v5/cust_architecture/collect_output/Bit Set to get AC during DC', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/collect_output/Bit Set to get AC during DC', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input', 0, 2, '');
annotate_port('gm_CustArch_v5/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 0, 2, '');
annotate_port('gm_CustArch_v5/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass', 0, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/DCtoAC_storage', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/DCtoAC_storage', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/process_and_retrieve/DCtoAC_storage', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/DCtoAC_storage', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/process_and_retrieve/DCtoAC_storage', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/multiplier', 0, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc', 0, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc1', 0, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc2', 0, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/gain', 0, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc3', 0, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/Sub', 0, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc5', 0, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc6', 0, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/adder', 0, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc7', 0, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/output_typeconvert_wire', 0, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/highpass_out1', 0, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/Add_out1bypassMux', 0, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/Add', 0, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/Add1', 0, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 1, 1, '');
annotate_port('gm_CustArch_v5/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/output_interpret/OutputStateMachine', 1, 1, '');
annotate_port('CustArch_v5/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 0, 2, '');
annotate_port('CustArch_v5/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
