open_system('gm_CustArch_v5');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/input_interpret_store_retrieve', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/input_interpret_store_retrieve', 0, 3, 'cp : 2.372 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/process_and_retrieve', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve', 1, 3, 'cp : 21.308 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input', 0, 2, 'cp : 2.372 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 0, 2, 'cp : 2.372 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass', 0, 1, 'cp : 21.016 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/process_and_retrieve/DCtoAC_storage', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/DCtoAC_storage', 1, 1, 'cp : 21.308 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/multiplier', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/multiplier', 0, 1, 'cp : 7.574 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc', 0, 1, 'cp : 9.508 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc1', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc1', 0, 1, 'cp : 14.892 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc2', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc2', 0, 1, 'cp : 11.442 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/gain', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/gain', 0, 1, 'cp : 14.892 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc3', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc3', 0, 1, 'cp : 11.442 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/Sub', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/Sub', 0, 1, 'cp : 12.958 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc5', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc5', 0, 1, 'cp : 12.958 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc6', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc6', 0, 1, 'cp : 16.826 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/adder', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/adder', 0, 1, 'cp : 16.826 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc7', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/dtc7', 0, 1, 'cp : 18.76 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/output_typeconvert_wire', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/output_typeconvert_wire', 0, 1, 'cp : 18.76 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/highpass_out1', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/highpass_out1', 0, 1, 'cp : 18.76 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/Add_out1bypassMux', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/Add_out1bypassMux', 0, 1, 'cp : 21.016 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/Add', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/Add', 0, 1, 'cp : 19.958 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/Add1', 'user2');
annotate_port('gm_CustArch_v5/cust_architecture/process_and_retrieve/highpass/Add1', 0, 1, 'cp : 3.57 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('CustArch_v5/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 'user1');
annotate_port('CustArch_v5/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 0, 2, 'cp : 2.372 ns');
annotate_port('CustArch_v5/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, 'cp : 21.308 ns');
