open_system('gm_CustArch_v3');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/input_interpret_store_retrieve', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/input_interpret_store_retrieve', 0, 3, 'cp : 2.372 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve', 1, 3, 'cp : 59.83 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input', 0, 2, 'cp : 2.372 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 0, 2, 'cp : 2.372 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass', 0, 1, 'cp : 59.538 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/DCtoAC_storage', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/DCtoAC_storage', 1, 1, 'cp : 59.83 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/multiplier', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/multiplier', 0, 1, 'cp : 7.574 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc', 0, 1, 'cp : 9.508 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc1', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc1', 0, 1, 'cp : 16.196 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc2', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc2', 0, 1, 'cp : 11.442 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/gain', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/gain', 0, 1, 'cp : 16.196 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc3', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc3', 0, 1, 'cp : 11.442 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/Sub', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/Sub', 0, 1, 'cp : 12.852 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc5', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc5', 0, 1, 'cp : 12.852 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc6', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc6', 0, 1, 'cp : 12.852 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/Sub1', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/Sub1', 0, 1, 'cp : 14.262 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc8', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc8', 0, 1, 'cp : 14.262 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc9', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc9', 0, 1, 'cp : 18.13 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/adder', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/adder', 0, 1, 'cp : 18.13 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/adder1', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/adder1', 0, 1, 'cp : 19.54 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc10', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc10', 0, 1, 'cp : 21.474 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/output_typeconvert_wire', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/output_typeconvert_wire', 0, 1, 'cp : 21.474 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/multiplier3', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/multiplier3', 0, 1, 'cp : 25.478 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc11', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc11', 0, 1, 'cp : 27.412 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc12', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc12', 0, 1, 'cp : 34.1 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc13', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc13', 0, 1, 'cp : 29.346 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/gain3', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/gain3', 0, 1, 'cp : 34.1 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc14', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc14', 0, 1, 'cp : 29.346 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/Sub2', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/Sub2', 0, 1, 'cp : 30.756 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc16', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc16', 0, 1, 'cp : 30.756 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc17', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc17', 0, 1, 'cp : 30.756 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/Sub3', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/Sub3', 0, 1, 'cp : 32.166 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc19', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc19', 0, 1, 'cp : 32.166 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc20', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc20', 0, 1, 'cp : 36.034 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/adder2', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/adder2', 0, 1, 'cp : 37.444 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/adder3', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/adder3', 0, 1, 'cp : 38.854 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc21', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc21', 0, 1, 'cp : 40.788 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/multiplier6', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/multiplier6', 0, 1, 'cp : 44.792 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc22', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc22', 0, 1, 'cp : 46.726 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc23', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc23', 0, 1, 'cp : 52.004 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc24', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc24', 0, 1, 'cp : 48.66 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/gain6', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/gain6', 0, 1, 'cp : 52.004 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc25', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc25', 0, 1, 'cp : 48.66 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/Sub4', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/Sub4', 0, 1, 'cp : 50.07 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc27', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc27', 0, 1, 'cp : 50.07 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc28', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc28', 0, 1, 'cp : 53.938 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/adder4', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/adder4', 0, 1, 'cp : 55.348 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc29', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/dtc29', 0, 1, 'cp : 57.282 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/output_typeconvert_wire1', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/output_typeconvert_wire1', 0, 1, 'cp : 57.282 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/highpass_out1', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/highpass_out1', 0, 1, 'cp : 21.474 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/lowpass_out1', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/lowpass_out1', 0, 1, 'cp : 57.282 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/Add_out1bypassMux', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/Add_out1bypassMux', 0, 1, 'cp : 59.538 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/Add', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/Add', 0, 1, 'cp : 58.48 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/Add1', 'user2');
annotate_port('gm_CustArch_v3/cust_architecture/process_and_retrieve/bandpass/Add1', 0, 1, 'cp : 3.57 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('CustArch_v3/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 'user1');
annotate_port('CustArch_v3/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 0, 2, 'cp : 2.372 ns');
annotate_port('CustArch_v3/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, 'cp : 59.83 ns');
