open_system('gm_CustArch_v13');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve', 0, 1, 'cp : 24.603 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1', 1, 1, 'cp : 24.603 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Memory3', 'user1');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Memory3', 0, 1, 'cp : 0.298 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter', 0, 1, 'cp : 24.482 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/Rate Transition', 'user1');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/Rate Transition', 1, 1, 'cp : 24.603 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass', 0, 1, 'cp : 22.067 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/Add1_out1bypassMux', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/Add1_out1bypassMux', 0, 1, 'cp : 24.482 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/Add', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/Add', 0, 1, 'cp : 1.496 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/Add1', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/Add1', 0, 1, 'cp : 23.424 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/t', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/t', 0, 1, 'cp : 3.43 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/filter_in_0_wire', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/filter_in_0_wire', 0, 1, 'cp : 3.43 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/multiplier', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/multiplier', 0, 1, 'cp : 7.434 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc', 0, 1, 'cp : 9.215 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc1', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc1', 0, 1, 'cp : 18.723 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc2', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc2', 0, 1, 'cp : 11.149 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/gain', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/gain', 0, 1, 'cp : 18.723 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc3', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc3', 0, 1, 'cp : 11.149 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/Sub', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/Sub', 0, 1, 'cp : 12.559 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc5', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc5', 0, 1, 'cp : 13.969 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc6', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc6', 0, 1, 'cp : 13.969 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/Sub1', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/Sub1', 0, 1, 'cp : 15.379 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc8', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc8', 0, 1, 'cp : 16.789 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/adder', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/adder', 0, 1, 'cp : 18.723 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/adder1', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/adder1', 0, 1, 'cp : 20.133 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc9', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/dtc9', 0, 1, 'cp : 22.067 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/output_typeconvert_wire', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/output_typeconvert_wire', 0, 1, 'cp : 22.067 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/mux', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/mux', 0, 1, 'cp : 22.067 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/filter_out_1', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/filter_out_1', 0, 1, 'cp : 22.067 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/filter_out1', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/filter_out1', 0, 1, 'cp : 22.067 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/Input Quantizer', 'user2');
annotate_port('gm_CustArch_v13/cust_architecture/process_and_retrieve/Filter_ch1/digital_filter/highpass/Input Quantizer', 0, 1, 'cp : 3.43 ns');
