open_system('pipe_in_v4');
open_system('gm_pipe_in_v4');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, 'Block not characterized');
hilite_system('pipe_in_v4/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 'user2');
annotate_port('pipe_in_v4/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, 'Block not characterized');
hilite_system('pipe_in_v4/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 'user2');
annotate_port('pipe_in_v4/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, 'Block not characterized');
hilite_system('pipe_in_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 'user2');
annotate_port('pipe_in_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, 'Block not characterized');
hilite_system('pipe_in_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 'user2');
annotate_port('pipe_in_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, 'Block not characterized');
hilite_system('pipe_in_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 'user2');
annotate_port('pipe_in_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, 'Block not characterized');
hilite_system('pipe_in_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 'user2');
annotate_port('pipe_in_v4/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 1, 1, 'Block not characterized');
hilite_system('pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 'user2');
annotate_port('pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 1, 1, 'Block not characterized');
hilite_system('pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 'user2');
annotate_port('pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 1, 1, 'Block not characterized');
hilite_system('pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 'user2');
annotate_port('pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 1, 1, 'Block not characterized');
hilite_system('pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 'user2');
annotate_port('pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 1, 1, 'Block not characterized');
hilite_system('pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 'user2');
annotate_port('pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 1, 1, 'Block not characterized');
hilite_system('pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 'user2');
annotate_port('pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 1, 1, 'Block not characterized');
hilite_system('pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 'user2');
annotate_port('pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 1, 1, 'Block not characterized');
hilite_system('pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 'user2');
annotate_port('pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 1, 1, 'Block not characterized');
hilite_system('pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 'user2');
annotate_port('pipe_in_v4/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/process_and_retrieve/DCtoAC_storage', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/process_and_retrieve/DCtoAC_storage', 1, 1, 'Block not characterized');
hilite_system('pipe_in_v4/cust_architecture/process_and_retrieve/DCtoAC_storage', 'user2');
annotate_port('pipe_in_v4/cust_architecture/process_and_retrieve/DCtoAC_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/process_and_retrieve/DCtoAC_storage', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/process_and_retrieve/DCtoAC_storage', 1, 1, 'Block not characterized');
hilite_system('pipe_in_v4/cust_architecture/process_and_retrieve/DCtoAC_storage', 'user2');
annotate_port('pipe_in_v4/cust_architecture/process_and_retrieve/DCtoAC_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 1, 'Block not characterized');
hilite_system('pipe_in_v4/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 'user2');
annotate_port('pipe_in_v4/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 1, 1, 'Block not characterized');
hilite_system('pipe_in_v4/cust_architecture/output_interpret/OutputStateMachine', 'user2');
annotate_port('pipe_in_v4/cust_architecture/output_interpret/OutputStateMachine', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/pipe_in_interpret/Chart1/Chart1', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/pipe_in_interpret/Chart1/Chart1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pipe_in_v4/cust_architecture/pipe_in_interpret/Chart1/Chart1', 'user2');
annotate_port('gm_pipe_in_v4/cust_architecture/pipe_in_interpret/Chart1/Chart1', 1, 1, 'Block not characterized');
hilite_system('pipe_in_v4/cust_architecture/pipe_in_interpret/Chart1', 'user2');
annotate_port('pipe_in_v4/cust_architecture/pipe_in_interpret/Chart1', 1, 1, 'Block not characterized');
