SLStudio.Utils.RemoveHighlighting(get_param('LocalMaximaAdaptiveThreshold', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_LocalMaximaAdaptiveThreshold', 'handle'));
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation', 0, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 1, 1, '');
annotate_port('LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 1, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 1, 1, '');
annotate_port('LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 1, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-2', 1, 1, '');
annotate_port('LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-2', 1, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-2', 1, 1, '');
annotate_port('LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-2', 1, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation', 0, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/n', 0, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/rms', 1, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/rms', 1, 1, '');
annotate_port('LocalMaximaAdaptiveThreshold/RMS_computation/rms', 1, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/rms', 1, 1, '');
annotate_port('LocalMaximaAdaptiveThreshold/RMS_computation/rms', 1, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/square_sum', 0, 2, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/square_sum', 1, 1, '');
annotate_port('LocalMaximaAdaptiveThreshold/RMS_computation/square_sum', 1, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/square_sum', 1, 1, '');
annotate_port('LocalMaximaAdaptiveThreshold/RMS_computation/square_sum', 1, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/Square Root1', 0, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/Square Root1', 1, 1, '');
annotate_port('LocalMaximaAdaptiveThreshold/RMS_computation/Square Root1', 1, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/Square Root1', 1, 1, '');
annotate_port('LocalMaximaAdaptiveThreshold/RMS_computation/Square Root1', 1, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation/rms_gain', 0, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation/Add', 0, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation/Add1', 0, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation/Add4', 0, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/adaptive_th_computation/Switch1', 0, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/buffer_counter/square_sum', 1, 1, '');
annotate_port('LocalMaximaAdaptiveThreshold/RMS_computation/buffer_counter/square_sum', 1, 1, '');
annotate_port('gm_LocalMaximaAdaptiveThreshold/RMS_computation/buffer_counter/square_sum', 1, 1, '');
annotate_port('LocalMaximaAdaptiveThreshold/RMS_computation/buffer_counter/square_sum', 1, 1, '');
annotate_port('LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 0, 2, '');
annotate_port('LocalMaximaAdaptiveThreshold/LocalMaxima/sample_t-1', 1, 1, '');
