// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\CustArch_v22\LocalMaximaAdaptiveThreshold.v
// Created: 2021-09-20 15:43:05
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// local_maxima_out              ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: LocalMaximaAdaptiveThreshold
// Source Path: LocalMaximaAdaptiveThreshold
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module LocalMaximaAdaptiveThreshold
          (clk,
           reset,
           clk_enable,
           filter_output,
           InputState,
           write_porcessing_addr_read_from_storage_addr_1,
           ce_out,
           local_maxima_out);


  input   clk;
  input   reset;
  input   clk_enable;
  input   [15:0] filter_output;  // uint16
  input   InputState;
  input   [8:0] write_porcessing_addr_read_from_storage_addr_1;  // ufix9
  output  ce_out;
  output  local_maxima_out;


  wire [15:0] RMS_computation_out1;  // uint16
  wire LocalMaxima_out1;


  RMS_computation u_RMS_computation (.clk(clk),
                                     .reset(reset),
                                     .enb(clk_enable),
                                     .filter_output(filter_output),  // uint16
                                     .write_porcessing_addr_read_from_storage_addr_1(write_porcessing_addr_read_from_storage_addr_1),  // ufix9
                                     .InputState(InputState),
                                     .adaptive_th(RMS_computation_out1)  // uint16
                                     );

  LocalMaxima u_LocalMaxima (.clk(clk),
                             .reset(reset),
                             .enb(clk_enable),
                             .adaptive_th(RMS_computation_out1),  // uint16
                             .filter_output(filter_output),  // uint16
                             .InputState(InputState),
                             .write_porcessing_addr_read_from_storage_addr_1(write_porcessing_addr_read_from_storage_addr_1),  // ufix9
                             .Out1(LocalMaxima_out1)
                             );

  assign local_maxima_out = LocalMaxima_out1;

  assign ce_out = clk_enable;

endmodule  // LocalMaximaAdaptiveThreshold

