// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\CustArch_v21\process_and_retrieve.v
// Created: 2021-10-12 23:33:16
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: process_and_retrieve
// Source Path: CustArch_v21/cust_architecture/process_and_retrieve
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module process_and_retrieve
          (clk,
           reset,
           enb,
           rd_address,
           InputState,
           current_value,
           read_from_processing_addr,
           OutputState,
           rd_dout);


  input   clk;
  input   reset;
  input   enb;
  input   [8:0] rd_address;  // ufix9
  input   [7:0] InputState;  // uint8
  input   [15:0] current_value;  // uint16
  input   [8:0] read_from_processing_addr;  // ufix9
  input   [7:0] OutputState;  // uint8
  output  [15:0] rd_dout;  // uint16


  reg [7:0] Delay_out1;  // uint8
  wire switch_compare_1;
  wire [15:0] filtering_out1;  // uint16
  wire [8:0] filtering_out2;  // ufix9
  wire [8:0] filtering_out3;  // ufix9
  wire filtering_out4;
  wire [15:0] spike;  // uint16
  wire [15:0] ProcessedData_storage_out1;  // uint16
  wire [15:0] ProcessedData_storage_out2;  // uint16
  wire [15:0] Switch_out1;  // uint16

  // The dual-port RAM in the input interpret subsystem introduces 
  // a sample of delay. Furthermore, I need one sample more of delay
  // due to the IIR filter --> overall delay of two samples
  // 
  // generally, all sample in the processing subsystem
  // are delayed by two samples --> the memories are 
  // needed for this reason
  // 
  // note that these RAM are too big.. I just need 160 and thus a reduced address port width  
  // 
  // rd_address from Output
  // 
  // data sent for processing
  // 
  // address sent for processing


  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= OutputState;
        end
      end
    end



  assign switch_compare_1 = Delay_out1 > 8'b00000110;



  filtering u_filtering (.clk(clk),
                         .reset(reset),
                         .enb(enb),
                         .current_sample(current_value),  // uint16
                         .In2(InputState),  // uint8
                         .In3(read_from_processing_addr),  // ufix9
                         .filter_output(filtering_out1),  // uint16
                         .write_porcessing_addr_read_from_storage_addr_1(filtering_out2),  // ufix9
                         .write_porcessing_addr_read_from_storage_addr_4(filtering_out3),  // ufix9
                         .wr_en(filtering_out4)
                         );

  spike_detection u_spike_detection (.clk(clk),
                                     .reset(reset),
                                     .enb(enb),
                                     .filter_output(filtering_out1),  // uint16
                                     .write_porcessing_addr_read_from_storage_addr_1(filtering_out2),  // ufix9
                                     .rd_addr(rd_address),  // ufix9
                                     .wr_en_filt(filtering_out4),
                                     .write_porcessing_addr_read_from_storage_addr_4(filtering_out3),  // ufix9
                                     .spike(spike)  // uint16
                                     );

  DualPortRAM_generic #(.AddrWidth(9),
                        .DataWidth(16)
                        )
                      u_ProcessedData_storage (.clk(clk),
                                               .enb(enb),
                                               .wr_din(filtering_out1),
                                               .wr_addr(filtering_out3),
                                               .wr_en(filtering_out4),
                                               .rd_addr(rd_address),
                                               .wr_dout(ProcessedData_storage_out1),
                                               .rd_dout(ProcessedData_storage_out2)
                                               );

  assign Switch_out1 = (switch_compare_1 == 1'b0 ? spike :
              ProcessedData_storage_out2);



  assign rd_dout = Switch_out1;

endmodule  // process_and_retrieve

