SLStudio.Utils.RemoveHighlighting(get_param('CustArch_v26', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_CustArch_v26', 'handle'));
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input', 0, 2, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 1, 4, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data', 0, 2, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses', 0, 4, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/AND2', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/Compare To Constant1', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/Compare To Constant5', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/Switch', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Bit Slice7', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Compare To Constant7', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch1', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch2', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch3', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch4', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch5', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch6', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_first_one_pos/Switch7', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Bitwise AND', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Bitwise AND1', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Compare To Constant7', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch1', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch2', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch3', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch4', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch5', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch6', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret incoming data/get_sources_and_RAM_addresses/find_next_chip_rollmap/Switch7', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/process_and_retrieve/PreviousData_storage', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/process_and_retrieve/PreviousData_storage', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/process_and_retrieve/PreviousData_storage', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/process_and_retrieve/PreviousData_storage', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/process_and_retrieve/ProcessedData_storage', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/process_and_retrieve/ProcessedData_storage', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/process_and_retrieve/ProcessedData_storage', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/process_and_retrieve/ProcessedData_storage', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/process_and_retrieve/pipe_in_interpret/pipe_in_refractory/Detect Change1', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/process_and_retrieve/pipe_in_interpret/pipe_in_refractory/Detect Change1', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/process_and_retrieve/pipe_in_interpret/pipe_in_refractory/refractory_RAM', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/process_and_retrieve/pipe_in_interpret/pipe_in_refractory/refractory_RAM', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/process_and_retrieve/pipe_in_interpret/pipe_in_refractory/refractory_RAM', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/process_and_retrieve/pipe_in_interpret/pipe_in_refractory/refractory_RAM', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/process_and_retrieve/pipe_in_interpret/pipe_in_th/Detect Change1', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/process_and_retrieve/pipe_in_interpret/pipe_in_th/Detect Change1', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/process_and_retrieve/pipe_in_interpret/pipe_in_th/refractory_RAM', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/process_and_retrieve/pipe_in_interpret/pipe_in_th/refractory_RAM', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/process_and_retrieve/pipe_in_interpret/pipe_in_th/refractory_RAM', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/process_and_retrieve/pipe_in_interpret/pipe_in_th/refractory_RAM', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-1', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-1', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-1', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-1', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-2', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-2', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-2', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/process_and_retrieve/spike_detection/LocalMaxima/sample_t-2', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/process_and_retrieve/spike_detection/refractory_period/spikes', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/process_and_retrieve/spike_detection/refractory_period/spikes', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/process_and_retrieve/spike_detection/refractory_period/spikes', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/process_and_retrieve/spike_detection/refractory_period/spikes', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/process_and_retrieve/spike_detection/refractory_period/timestamp_before', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/process_and_retrieve/spike_detection/refractory_period/timestamp_before', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/process_and_retrieve/spike_detection/refractory_period/timestamp_before', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/process_and_retrieve/spike_detection/refractory_period/timestamp_before', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 0, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 4, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 1, 1, '');
annotate_port('gm_CustArch_v26/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 1, 1, '');
annotate_port('CustArch_v26/cust_architecture/output_interpret/OutputStateMachine', 1, 1, '');
