open_system('CustArch_v21');
open_system('gm_CustArch_v21');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/collect_output', 'user2');
hilite_system('CustArch_v21/cust_architecture/collect_output', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve', 'user2');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering', 'user2');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering', 'user2');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR', 'user1');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 'user1');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 'user1');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData1_storage', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 'user1');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 'user1');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering/PreviousData2_storage', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR/HP_Butter_2nd', 'user1');
hilite_system('CustArch_v21/cust_architecture/process_and_retrieve/filtering/two_pole_IIR/HP_Butter_2nd', 'user1');
