// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\CustArchitecture\processing_output_logic.v
// Created: 2021-10-26 14:22:20
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: processing_output_logic
// Source Path: CustArchitecture/cust_architecture/processing_output_logic
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module processing_output_logic
          (clk,
           reset,
           enb,
           OutputState,
           filtered,
           spike,
           to_output_interpret_collect_output);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] OutputState;  // uint8
  input   [15:0] filtered;  // uint16
  input   [15:0] spike;  // uint16
  output  [15:0] to_output_interpret_collect_output;  // uint16


  reg [7:0] Delay_out1;  // uint8
  wire switch_compare_1;
  wire [15:0] Switch_out1;  // uint16


  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= OutputState;
        end
      end
    end



  assign switch_compare_1 = Delay_out1 > 8'b00000110;



  assign Switch_out1 = (switch_compare_1 == 1'b0 ? spike :
              filtered);



  assign to_output_interpret_collect_output = Switch_out1;

endmodule  // processing_output_logic

