vlib work
vlog  get_data_only_when_enabled.v
vlog  getting_address_and_enable_for_Magic_and_Timestamps.v
vlog  DualPortRAM_generic.v
vlog  read_from_magic_and_timestamp.v
vlog  collect_output.v
vlog  RAM_address_definition.v
vlog  condition_to_count_DAC_or_ADC.v
vlog  RAM_address_channel_data.v
vlog  enable_source_chip_transmission.v
vlog  find_first_one_pos.v
vlog  find_next_chip_rollmap.v
vlog  get_sources_and_RAM_addresses.v
vlog  interpret_incoming_data.v
vlog  Interpret_to_RAM_input.v
vlog  store_and_retrieve_input.v
vlog  InputStateMachine.v
vlog  input_interpret_store_retrieve.v
vlog  Output_State_to_RAM_address_to_read.v
vlog  Detect_change_ch_cnt.v
vlog  find_next_chip_rollmap_block.v
vlog  reading_address.v
vlog  get_enabled_timings.v
vlog  Interpret_to_RAM_output.v
vlog  OutputStateMachine.v
vlog  output_interpret.v
vlog  HP_Butter_1st.v
vlog  one_pole_IIR.v
vlog  LocalMaxima.v
vlog  refractory_period.v
vlog  spike_detection.v
vlog  process_and_retrieve.v
vlog  cust_architecture.v
