// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\pipe_in_v3\Chart1.v
// Created: 2021-09-08 16:45:35
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Chart1
// Source Path: pipe_in_v3/cust_architecture/pipe_in_interpret/Chart1
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Chart1
          (clk,
           reset,
           enb,
           pipe_in_en,
           PipeInState);

  // Default encoded enumeration values for type is_Chart1
  parameter is_Chart1_IN_state_hard_threshold = 1'd0, is_Chart1_IN_state_refractory = 1'd1;

  input   clk;
  input   reset;
  input   enb;
  input   pipe_in_en;
  output  [7:0] PipeInState;  // uint8


  reg  is_Chart1;  // uint8
  reg [7:0] PipeInState_1;  // uint8
  reg  is_Chart1_next;  // enum type is_Chart1 (2 enums)


  always @(posedge clk or posedge reset)
    begin : Chart1_1_process
      if (reset == 1'b1) begin
        is_Chart1 <= is_Chart1_IN_state_hard_threshold;
      end
      else begin
        if (enb) begin
          is_Chart1 <= is_Chart1_next;
        end
      end
    end

  always @(is_Chart1, pipe_in_en) begin
    is_Chart1_next = is_Chart1;
    case ( is_Chart1)
      is_Chart1_IN_state_hard_threshold :
        begin
          if (pipe_in_en) begin
            is_Chart1_next = is_Chart1_IN_state_refractory;
            PipeInState_1 = 8'd1;
          end
          else begin
            PipeInState_1 = 8'd0;
          end
        end
      default :
        begin
          //case IN_state_refractory:
          is_Chart1_next = is_Chart1_IN_state_hard_threshold;
          PipeInState_1 = 8'd0;
        end
    endcase
  end



  assign PipeInState = PipeInState_1;

endmodule  // Chart1

