SLStudio.Utils.RemoveHighlighting(get_param('cust_arch_18', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_cust_arch_18', 'handle'));
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/collect_output/Bit Set to get AC during DC', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/collect_output/Bit Set to get AC during DC', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input', 0, 2, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 1, 4, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data', 0, 2, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources', 0, 4, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/find_first_one_pos', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/position_to_bitmask', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/AND2', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/Compare To Constant1', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/Compare To Constant5', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/Switch', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/find_first_one_pos/Bit Slice7', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/find_first_one_pos/Compare To Constant7', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/find_first_one_pos/Switch', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/find_first_one_pos/Switch1', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/find_first_one_pos/Switch2', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/find_first_one_pos/Switch3', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/find_first_one_pos/Switch4', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/find_first_one_pos/Switch5', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/find_first_one_pos/Switch6', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/find_first_one_pos/Switch7', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/position_to_bitmask/Bitwise AND', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/position_to_bitmask/Bitwise AND1', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/position_to_bitmask/Compare To Constant7', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/position_to_bitmask/Switch', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/position_to_bitmask/Switch1', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/position_to_bitmask/Switch2', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/position_to_bitmask/Switch3', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/position_to_bitmask/Switch4', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/position_to_bitmask/Switch5', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/position_to_bitmask/Switch6', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/Interpret_to_RAM_input/interpret data/get_sources/position_to_bitmask/Switch7', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Detect Change', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Detect Change', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate1', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate1', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate2', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate2', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate3', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate3', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate4', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate4', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate5', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate5', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate6', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Subsystem/Bit Rotate6', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Triggered Subsystem/Bit Rotate', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/output_interpret/Interpret_to_RAM_output/get enabled timings /Triggered Subsystem/Bit Rotate', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/process_and_retrieve/HPF_storage', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/process_and_retrieve/HPF_storage', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/process_and_retrieve/HPF_storage', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/process_and_retrieve/HPF_storage', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/process_and_retrieve/LPF_storage', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/process_and_retrieve/LPF_storage', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/process_and_retrieve/LPF_storage', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/process_and_retrieve/LPF_storage', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 0, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 4, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/input_interpret_store_retrieve/InputStateMachine/InputStateMachine', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 1, 1, '');
annotate_port('gm_cust_arch_18/cust_architecture/output_interpret/OutputStateMachine/OutputStateMachine', 1, 1, '');
annotate_port('cust_arch_18/cust_architecture/output_interpret/OutputStateMachine', 1, 1, '');
