vlib work
vlog  get_data_only_when_enabled.v
vlog  getting_address_and_enable_for_Magic_and_Timestamps.v
vlog  DualPortRAM_generic.v
vlog  read_from_magic_and_timestamp.v
vlog  collect_output.v
vlog  Input_State_to_RAM_address_to_write.v
vlog  condition_to_count_DAC_or_ADC.v
vlog  Subsystem.v
vlog  Triggered_Subsystem.v
vlog  find_first_one_pos.v
vlog  position_to_bitmask.v
vlog  get_sources.v
vlog  interpret_data.v
vlog  Interpret_to_RAM_input.v
vlog  store_and_retrieve_input.v
vlog  InputStateMachine.v
vlog  input_interpret_store_retrieve.v
vlog  Output_State_to_RAM_address_to_read.v
vlog  Detect_Change.v
vlog  Subsystem_block.v
vlog  Triggered_Subsystem_block.v
vlog  get_enabled_timings.v
vlog  Interpret_to_RAM_output.v
vlog  OutputStateMachine.v
vlog  output_interpret.v
vlog  pipe_in_interpret.v
vlog  Filter1.v
vlog  one_pole_IIR.v
vlog  process_and_retrieve.v
vlog  cust_architecture.v
