open_system('CustArchitecture');
open_system('gm_CustArchitecture');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/Butter_1st_HP', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/Butter_1st_HP', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/Butter_1st_HP', 'user2');
annotate_port('CustArchitecture/cust_architecture/Butter_1st_HP', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/Butter_1st_HP/Subsystem', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/Butter_1st_HP/Subsystem', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/Butter_1st_HP/Subsystem', 'user2');
annotate_port('CustArchitecture/cust_architecture/Butter_1st_HP/Subsystem', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/Butter_1st_HP/ProcessedData_storage', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/Butter_1st_HP/ProcessedData_storage', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/Butter_1st_HP/ProcessedData_storage', 'user2');
annotate_port('CustArchitecture/cust_architecture/Butter_1st_HP/ProcessedData_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/Butter_1st_HP/ProcessedData_storage', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/Butter_1st_HP/ProcessedData_storage', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/Butter_1st_HP/ProcessedData_storage', 'user2');
annotate_port('CustArchitecture/cust_architecture/Butter_1st_HP/ProcessedData_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/Butter_1st_HP/Subsystem/one_pole_IIR', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/Butter_1st_HP/Subsystem/one_pole_IIR', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/Butter_1st_HP/Subsystem/one_pole_IIR', 'user2');
annotate_port('CustArchitecture/cust_architecture/Butter_1st_HP/Subsystem/one_pole_IIR', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/Butter_1st_HP/Subsystem/PreviousData_storage', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/Butter_1st_HP/Subsystem/PreviousData_storage', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/Butter_1st_HP/Subsystem/PreviousData_storage', 'user2');
annotate_port('CustArchitecture/cust_architecture/Butter_1st_HP/Subsystem/PreviousData_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/Butter_1st_HP/Subsystem/PreviousData_storage', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/Butter_1st_HP/Subsystem/PreviousData_storage', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/Butter_1st_HP/Subsystem/PreviousData_storage', 'user2');
annotate_port('CustArchitecture/cust_architecture/Butter_1st_HP/Subsystem/PreviousData_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/Butter_1st_HP/Subsystem/one_pole_IIR/HP_Butter_1st', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/Butter_1st_HP/Subsystem/one_pole_IIR/HP_Butter_1st', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/Butter_1st_HP/Subsystem/one_pole_IIR/HP_Butter_1st', 'user2');
annotate_port('CustArchitecture/cust_architecture/Butter_1st_HP/Subsystem/one_pole_IIR/HP_Butter_1st', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 'user2');
annotate_port('CustArchitecture/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 'user2');
annotate_port('CustArchitecture/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 'user2');
annotate_port('CustArchitecture/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 'user2');
annotate_port('CustArchitecture/cust_architecture/input_interpret_store_retrieve/store_and_retrieve_input/input_storage_for_processing', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/output_interpret_collect_output/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 'user2');
annotate_port('CustArchitecture/cust_architecture/output_interpret_collect_output/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/output_interpret_collect_output/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 'user2');
annotate_port('CustArchitecture/cust_architecture/output_interpret_collect_output/collect_output/read_from_magic_and_timestamp/input_RAM_for_MagicNumber_TimeStamps', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 'user2');
annotate_port('CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /Detect change ch cnt', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 'user2');
annotate_port('CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /find_next_chip_rollmap/Bit Rotate', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 'user2');
annotate_port('CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 'user2');
annotate_port('CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 'user2');
annotate_port('CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 'user2');
annotate_port('CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 'user2');
annotate_port('CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 'user2');
annotate_port('CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate5', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 'user2');
annotate_port('CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/Interpret_to_RAM_output/get_enabled_timings /reading_address/Bit Rotate6', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/spike_detection/LocalMaxima', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/spike_detection/LocalMaxima', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/spike_detection/LocalMaxima', 'user2');
annotate_port('CustArchitecture/cust_architecture/spike_detection/LocalMaxima', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/spike_detection/refractory_period', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/spike_detection/refractory_period', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/spike_detection/refractory_period', 'user2');
annotate_port('CustArchitecture/cust_architecture/spike_detection/refractory_period', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/spike_detection/LocalMaxima/sample_t-1', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/spike_detection/LocalMaxima/sample_t-1', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/spike_detection/LocalMaxima/sample_t-1', 'user2');
annotate_port('CustArchitecture/cust_architecture/spike_detection/LocalMaxima/sample_t-1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/spike_detection/LocalMaxima/sample_t-1', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/spike_detection/LocalMaxima/sample_t-1', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/spike_detection/LocalMaxima/sample_t-1', 'user2');
annotate_port('CustArchitecture/cust_architecture/spike_detection/LocalMaxima/sample_t-1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/spike_detection/LocalMaxima/sample_t-2', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/spike_detection/LocalMaxima/sample_t-2', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/spike_detection/LocalMaxima/sample_t-2', 'user2');
annotate_port('CustArchitecture/cust_architecture/spike_detection/LocalMaxima/sample_t-2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/spike_detection/LocalMaxima/sample_t-2', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/spike_detection/LocalMaxima/sample_t-2', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/spike_detection/LocalMaxima/sample_t-2', 'user2');
annotate_port('CustArchitecture/cust_architecture/spike_detection/LocalMaxima/sample_t-2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/spike_detection/refractory_period/spikes', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/spike_detection/refractory_period/spikes', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/spike_detection/refractory_period/spikes', 'user2');
annotate_port('CustArchitecture/cust_architecture/spike_detection/refractory_period/spikes', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/spike_detection/refractory_period/spikes', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/spike_detection/refractory_period/spikes', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/spike_detection/refractory_period/spikes', 'user2');
annotate_port('CustArchitecture/cust_architecture/spike_detection/refractory_period/spikes', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/spike_detection/refractory_period/timestamp_before', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/spike_detection/refractory_period/timestamp_before', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/spike_detection/refractory_period/timestamp_before', 'user2');
annotate_port('CustArchitecture/cust_architecture/spike_detection/refractory_period/timestamp_before', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/spike_detection/refractory_period/timestamp_before', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/spike_detection/refractory_period/timestamp_before', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/spike_detection/refractory_period/timestamp_before', 'user2');
annotate_port('CustArchitecture/cust_architecture/spike_detection/refractory_period/timestamp_before', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/input_interpret_store_retrieve/InputStateMachine/IIT_Genoa_Intan_HDL_blocks_c3_InputStateMachine', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/input_interpret_store_retrieve/InputStateMachine/IIT_Genoa_Intan_HDL_blocks_c3_InputStateMachine', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/input_interpret_store_retrieve/InputStateMachine/IIT_Genoa_Intan_HDL_blocks_c3_InputStateMachine', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/input_interpret_store_retrieve/InputStateMachine/IIT_Genoa_Intan_HDL_blocks_c3_InputStateMachine', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 'user2');
annotate_port('CustArchitecture/cust_architecture/input_interpret_store_retrieve/InputStateMachine', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/OutputStateMachine/IIT_Genoa_Intan_HDL_blocks_c1_OutputStateMachine', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/OutputStateMachine/IIT_Genoa_Intan_HDL_blocks_c1_OutputStateMachine', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/OutputStateMachine/IIT_Genoa_Intan_HDL_blocks_c1_OutputStateMachine', 'user2');
annotate_port('gm_CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/OutputStateMachine/IIT_Genoa_Intan_HDL_blocks_c1_OutputStateMachine', 1, 1, 'Block not characterized');
hilite_system('CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/OutputStateMachine', 'user2');
annotate_port('CustArchitecture/cust_architecture/output_interpret_collect_output/output_interpret/OutputStateMachine', 1, 1, 'Block not characterized');
