// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\CustArchitecture\spike_check.v
// Created: 2021-10-26 14:22:20
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: spike_check
// Source Path: CustArchitecture/cust_architecture/spike_detection/spike_check
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module spike_check
          (detection_check,
           refractory_check,
           spike_check_1);


  input   detection_check;
  input   refractory_check;
  output  spike_check_1;


  wire Logical_Operator_out1;


  assign Logical_Operator_out1 = detection_check & refractory_check;



  assign spike_check_1 = Logical_Operator_out1;

endmodule  // spike_check

